FROM maven:3.5-jdk-8

RUN mkdir -p /mvn-dummy-project
ADD pom.xml /mvn-dummy-project
RUN cd /mvn-dummy-project \
  && mvn dependency:go-offline \
  && cd / \
  && rm -rf /mvn-dummy-project

ENTRYPOINT ["/usr/bin/mvn"]
